import ExcelJS from 'exceljs';

import { IEmi } from '@/types/emi.types';
import { CurrencyFormatPreferences } from '@/utils/numberFormat';

import { applyHeaderStyle, applyLabelCell, applyValueCell, fmtDate, fmtPct, getCurrencyNumFmt } from './shared';

const BLUE = '1E40AF';
const BLUE_MID = '3B82F6';
const EVEN_ROW = 'EFF6FF';
const TOTALS_BG = '1E3A5F';

function addSummarySheet(wb: ExcelJS.Workbook, emi: IEmi, currencyFmt: string) {
    const ws = wb.addWorksheet('Summary');
    ws.properties.defaultColWidth = 22;
    ws.getColumn(1).width = 30;
    ws.getColumn(2).width = 28;

    // Title block
    ws.mergeCells('A1:B1');
    const titleCell = ws.getCell('A1');
    titleCell.value = emi.itemName;
    titleCell.font = { bold: true, size: 16, color: { argb: 'FFFFFF' } };
    titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BLUE } };
    titleCell.alignment = { horizontal: 'left', vertical: 'middle', indent: 1 };
    ws.getRow(1).height = 36;

    ws.mergeCells('A2:B2');
    const subtitleCell = ws.getCell('A2');
    subtitleCell.value = `${emi.tag ? `Category: ${emi.tag}` : 'EMI Report'}   |   Status: ${emi.isCompleted ? 'Completed' : 'Active'}   |   Generated: ${fmtDate(new Date())}`;
    subtitleCell.font = { size: 8, color: { argb: '6B7280' }, italic: true };
    subtitleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'EFF6FF' } };
    subtitleCell.alignment = { horizontal: 'left', vertical: 'middle', indent: 1 };
    ws.getRow(2).height = 18;

    const addSection = (title: string, startRow: number, rows: [string, string | number | null, string?][]) => {
        ws.mergeCells(`A${startRow}:B${startRow}`);
        const hCell = ws.getCell(`A${startRow}`);
        hCell.value = title;
        applyHeaderStyle(hCell, BLUE_MID);
        ws.getRow(startRow).height = 20;

        rows.forEach(([label, value, fmt], i) => {
            const r = startRow + 1 + i;
            const lc = ws.getCell(`A${r}`);
            const vc = ws.getCell(`B${r}`);
            lc.value = label;
            applyLabelCell(lc);
            if (typeof value === 'number' && fmt) {
                vc.value = value;
                vc.numFmt = fmt;
            } else {
                vc.value = value ?? '—';
            }
            applyValueCell(vc);
            vc.alignment = { horizontal: 'right' };
        });
    };

    let row = 4;

    addSection('LOAN DETAILS', row, [
        ['Principal', emi.principal, currencyFmt],
        ['Interest Rate', fmtPct(emi.interestRate)],
        ['Tenure', `${emi.tenure} months`],
        ['Monthly EMI', emi.emi, currencyFmt],
        ...(emi.gst > 0 ? [['GST Rate', fmtPct(emi.gst)] as [string, string]] : []),
        ...(emi.interestDiscount && emi.interestDiscount > 0
            ? [
                  [
                      'Interest Discount',
                      emi.interestDiscountType === 'percent' ? fmtPct(emi.interestDiscount) : emi.interestDiscount,
                      emi.interestDiscountType === 'amount' ? currencyFmt : undefined,
                  ] as [string, string | number, string?],
              ]
            : []),
    ]);

    row += 3 + (emi.gst > 0 ? 1 : 0) + (emi.interestDiscount && emi.interestDiscount > 0 ? 1 : 0);

    addSection('FINANCIAL TOTALS', row, [
        ['Total Loan Amount', emi.totalLoan, currencyFmt],
        ['Total Interest', emi.totalInterest, currencyFmt],
        ...(emi.gst > 0 ? [['Total GST', emi.totalGST ?? 0, currencyFmt] as [string, number, string]] : []),
        ['EMIs Paid', `${emi.totalPaidEMIs} of ${emi.tenure}`],
        ['Remaining Tenure', `${emi.remainingTenure} months`],
        ['Remaining Balance', emi.remainingBalance, currencyFmt],
    ]);

    row += 8 + (emi.gst > 0 ? 1 : 0);

    addSection('KEY DATES', row, [
        ['Start Date', fmtDate(emi.billDate)],
        ['End Date', fmtDate(emi.endDate)],
    ]);

    row += 4;

    if (emi.isSplit && emi.mySplit) {
        addSection('SPLIT DETAILS', row, [
            ['Your Split Percentage', fmtPct(emi.mySplit.splitPercentage)],
            ['Your Monthly Contribution', emi.mySplitAmount ?? 0, currencyFmt],
        ]);
        row += 4;
    }

    if (emi.notes) {
        addSection('NOTES', row, [['Notes', emi.notes]]);
        row += 3;
    }

    // Footer
    const footerRow = row + 1;
    ws.mergeCells(`A${footerRow}:B${footerRow}`);
    const fc = ws.getCell(`A${footerRow}`);
    fc.value = 'Generated by Emitrax';
    fc.font = { size: 7, italic: true, color: { argb: '9CA3AF' } };
}

function addAmortizationSheet(wb: ExcelJS.Workbook, emi: IEmi, currencyFmt: string) {
    const ws = wb.addWorksheet('Amortization Schedule');
    const hasGst = emi.gst > 0;

    const headers = ['#', 'Bill Date', 'EMI', 'Interest', 'Principal Paid', 'Balance'];
    const colWidths = [6, 18, 18, 18, 18, 18];
    if (hasGst) {
        headers.push('GST', 'Total w/ GST');
        colWidths.push(10, 20);
    }

    headers.forEach((h, i) => {
        const col = ws.getColumn(i + 1);
        col.width = colWidths[i];
        const cell = ws.getCell(1, i + 1);
        cell.value = h;
        applyHeaderStyle(cell, BLUE);
    });
    ws.getRow(1).height = 22;
    ws.views = [{ state: 'frozen', ySplit: 1 }];
    ws.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: headers.length } };

    let totalEmi = 0,
        totalInterest = 0,
        totalPrincipal = 0,
        totalGst = 0;

    (emi.amortizationSchedules ?? []).forEach((s, i) => {
        const r = i + 2;
        const emiVal = Number(s.emi);
        const interestVal = Number(s.interest);
        const principalVal = Number(s.principalPaid);
        const balanceVal = Number(s.balance);
        const gstAmt = emiVal * ((s.gst ?? 0) / 100);
        const totalWithGst = emiVal + gstAmt;

        totalEmi += emiVal;
        totalInterest += interestVal;
        totalPrincipal += principalVal;
        totalGst += gstAmt;

        const isEven = i % 2 === 0;
        const rowValues: (number | string)[] = [
            s.month,
            fmtDate(s.billDate),
            emiVal,
            interestVal,
            principalVal,
            balanceVal,
        ];
        if (hasGst) {
            rowValues.push(gstAmt, totalWithGst);
        }

        rowValues.forEach((v, ci) => {
            const cell = ws.getCell(r, ci + 1);
            cell.value = v;
            if (isEven) {
                cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: EVEN_ROW } };
            }
            cell.border = { bottom: { style: 'hair', color: { argb: 'E5E7EB' } } };
            cell.font = { size: 9 };

            // Apply currency format to numeric columns
            if (ci >= 2) {
                cell.numFmt = currencyFmt;
                cell.alignment = { horizontal: 'right' };
            } else if (ci === 0) {
                cell.alignment = { horizontal: 'center' };
            }
        });
    });

    // Totals row
    const totalsRow = (emi.amortizationSchedules?.length ?? 0) + 2;
    const totalsValues: (string | number)[] = ['', 'Totals', totalEmi, totalInterest, totalPrincipal, 0];
    if (hasGst) {
        totalsValues.push(totalGst, totalEmi + totalGst);
    }

    totalsValues.forEach((v, ci) => {
        const cell = ws.getCell(totalsRow, ci + 1);
        cell.value = v === 0 && ci === 5 ? '' : v;
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: TOTALS_BG } };
        cell.font = { bold: true, color: { argb: 'FFFFFF' }, size: 9 };
        if (ci >= 2 && typeof v === 'number' && v !== 0) {
            cell.numFmt = currencyFmt;
            cell.alignment = { horizontal: 'right' };
        }
        if (ci === 1) cell.font = { ...cell.font, italic: true };
    });

    ws.getRow(totalsRow).height = 20;
}

export function buildDetailedTemplate(wb: ExcelJS.Workbook, emi: IEmi, currencyPrefs: CurrencyFormatPreferences) {
    wb.creator = 'Emitrax';
    const currencyFmt = getCurrencyNumFmt(currencyPrefs.currency);
    addSummarySheet(wb, emi, currencyFmt);
    addAmortizationSheet(wb, emi, currencyFmt);
}
